task :test do
  run_cmd = FileList['*.rb'].map { |f| "require \"#{File.expand_path(f)}\";" }.join
  output = `ruby -e '#{run_cmd}'`
  status = $?.exitstatus
  if (status == 0)
    puts "CONGRATULATIONS!  All tests pass."
  else
    puts "#{status} assertions have failed!"
    puts output
  end
end

task :default => :test


